### ISSUE TITLE
I can't send anything

### ISSUE THREAD

**Issue by raadraad** [btcontract/wallet#24] opened 2017-06-28 20:59 UTC
My balance: 0.10080223

When I try to send $32 (0.01240478), I get the error "Transaction failed because 1240478 exceeds the total amount of coins in this wallet. Please add some funds and then try again."

**Comment by btcontract** [comment] 2017-06-28 21:17
Thanks for reporting this, I'll give it a look.  

Meanwhile, if you need to send a transaction ASAP you can extract a mnemonic code (app menu -> wallet settings -> view mnemonic code) and use it to restore a balance in MultiBit HD for desktop (our wallets are compatible, use BIP32 option when restoring).

**Comment by raadraad** [comment] 2017-06-28 22:11
Thank you!

**Comment by raadraad** [comment] 2017-07-01 05:52
I've tried MultiBit, but a lot of my balance comes out as 'unconfirmed' and when I repair the wallet, that amount changes, sometimes less, sometimes more. Sometimes more than half the balance!

**Comment by raadraad** [comment] 2017-07-01 05:52
Also, still getting the original issue.

**Comment by btcontract** [comment] 2017-07-01 11:00
Can't reproduce an issue in my test environment. 

May I ask if the total balance of BTC 0.10080223 in your wallet consists of a large number of very small transactions?

**Comment by btcontract** [comment] 2017-07-01 11:35
Also, there indeed was a UI bug at the very least.  

My suspicion is that somehow wallet adds a ridiculously high fee to 0.01240478 which results in final transaction value exceeding a wallet balance (large number of small incoming transactions may be the reason but still it seems like resulting fee is way too high even if that's the case).  

I've just issued an update via Google Play which will be reporting by how much exactly a final transaction sum + fees exceeds a wallet balance. Please let me know what it says once an app is updated.

**Comment by raadraad** [comment] 2017-07-01 14:47
Yes, it does consist of a large number of small transactions.

**Comment by raadraad** [comment] 2017-07-02 03:15
Thanks, the fee was the issue. Apparently the transaction was 26-27 kB so the fees were enormous.

Why was the size so large? Because it was an accumulation of many small transactions?

The lowest fee option was also 0.001. Maybe you can add more options for that? MultiBit lets me set it lower with their slider.

**Comment by btcontract** [comment] 2017-07-02 04:31
Yes, a transaction is constructed from inputs (which use unspent outputs from previous incoming transactions) and each input contributes a lot to the overall transaction size in kB so when a lot of small incoming transactions is used to form a new outgoing one it's fee may indeed be extremely large compared to value transferred.

Have you managed to spend the funds using either of wallets? My wallet is optimized for simplicity so fee options are very basic and it works most of the time, plus setting a feerate too low increases a risk of miners not accepting a transaction at all. 

But such a large transactions are a bit special in a way that miners do have an incentive to accept them even if the fee is very low (because a lot of unspent outputs are eliminated). I think I'll consider using more detailed options for such a special transactions.

**Comment by btcontract** [comment] 2017-07-06 12:50
Closing this, let me know if nay help is still needed.

**Closed by btcontract** 2017-07-06 12:50 UTC
