### ISSUE TITLE
When fundung a channel add option to set fees

### ISSUE THREAD

**Issue by jordan-greg** [btcontract/wallet#61] opened 2021-08-28 14:44 UTC
It would be good to be able to set sats/byte with at least one decimal place

**Comment by btcontract** [comment] 2021-08-28 15:56
It's actually not a coincidence that specifically for channel funding transactions a custom feerate is not present, it's basically a combination of two factors:

1. Channel funding transaction can not be RBF at least for now with current LN protocol design so if user initially sets too low a feerate there will be no way to bump it later.
2. The way most LN nodes work is they wait for some rather short period of time (typically a few days) for channel funding to become confirmed, and then they just drop a pending channel. If that happens a user on the other side will have to force-close a channel and lose on fees for nothing.

Given these factors channel funding feerate is chosen to be relatively high and not adjustable.

**Comment by jordan-greg** [comment] 2021-08-29 10:27
> Channel funding transaction can not be RBF at least for now with current LN protocol design so if user initially sets too low a feerate there will be no way to bump it later.

This is not true, fee can be bumped via CPFP trick (https://lightningwiki.net/index.php/Bumping_fee_for_lightning_channel_open). (Requirement is ofc the change from funding tx.)

-------

I agree that it is probably not for average user, but maybe this can be added as checkbox in some Advanced Settings for power users to enable them to change it manually.

**Comment by btcontract** [comment] 2021-08-29 18:42
Yeah, haven't thought of possibility to use CPFP on change utxo, although this will not always work because wallet allows to send all chain funds into channel, so there may be no change.

In any case CPFP is not implemented in a wallet yet and I'm not sure it makes sense to allow fee adjustment even after it's present because of no-change possibility.

**Comment by btcontract** [comment] 2021-09-03 10:55
Fixed in https://github.com/btcontract/wallet/issues/68 by adding a warning for now. Hopefully future protocol changes will make bumping of funding tx safe and robust (RBF-based), this restriction will be lifted then.

**Closed by btcontract** 2021-09-03 10:55 UTC

**Comment by f-hayek** [comment] 2021-09-09 10:16
I can't initiate a channel open from an external node to SBW. SBW says "Feerate too different". SBW feerate is like 19000 sats but my external node feerate is ~ 250 sats (reasonable because the mempool is empty). Can this be relaxed somehow ?

**Comment by btcontract** [comment] 2021-09-09 10:24
Currently the only solution is to wait until feerate normalizes in SBW. 

It averages a history of prior feerates to ease out possible outlier spikes but the downside of it is it may take more time (a day or so) for local feerate view to come to terms with current network view.
