### ISSUE TITLE
Cannot connect to onion Electrum server even with tor enabled

### ISSUE THREAD

**Issue by ElucGeek** [btcontract/wallet#127] opened 2021-12-18 21:43 UTC
Hello, I've just started using Umbrel and SBW. I tried to add the Umbrel Electrum server, that is an onion address, to SBW while I enabled tor mode before (within the app, not with orbot, as it looks like Tor is now natively integrated). But the status always stay offline.
I tried to enable orbot and add SBW to the VPN with tor option enabled in SBW, then with tor option disabled. Then with orbot disabled. It always say offline.
How can I investigate if it's a problem on SBW side or Umbrel side?

**Comment by btcontract** [comment] 2021-12-20 19:13
A good place to look into is Electrum logs on umbrel side: there should be some connection info there if connect does happen and then drops for some reason. Other than that, if you can share an Electrum onion address here or privately I can try to investigate it on SBW side. (my contacts are listed at sbw.app site).

**Comment by ElucGeek** [comment] 2021-12-20 20:31
Thanks @btcontract for taking the time. I prefer not to share in public my Electrum server, I will send you an email but don't you have a PGP key?

**Comment by btcontract** [comment] 2021-12-20 20:39
I do, here it is: https://sbw.app/akumaigorodski.asc

**Comment by btcontract** [comment] 2021-12-27 17:58
Nothing received so far, feel free to reopen if issue persists.

**Comment by ElucGeek** [comment] 2021-12-27 19:08
Sorry, I still have the issue and did send you my onion spectrum sever address by email immediately after you post your key, to the email in the key (gmail) not the one on the website (outlook.com). I can re-send to you outlook address if you prefer.

**Comment by btcontract** [comment] 2021-12-27 19:11
Oh sorry, got it, I don't check that email too often. Will take a look at it.

**Comment by btcontract** [comment] 2021-12-28 09:02
Looks like the issue is that SSL is not used on your Electrum server since provided address starts working if I turn SSL off on wallet side.

SBW convention is that Electrum server must have an SSL, but certificate may be self-signed.

**Comment by btcontract** [comment] 2021-12-28 10:09
Fixed in https://github.com/btcontract/wallet/commit/44dfe70f2c05862e83e38a45620b59247d95de9e, will be on since next update. By convention, if Electrum server port is 50001 then SSL won't be used, this should work for your case.

**Comment by ElucGeek** [comment] 2021-12-28 10:56
Nice, thanks for the fast fix. But shouldn't you made only for onion that SSL is not required?

**Comment by btcontract** [comment] 2021-12-28 11:13
SSL is enforced on all default Electrum servers, but if user explicitly wishes to use cleartext I don't see why app should prevent that.

**Comment by btcontract** [comment] 2022-01-12 18:09
Should be fixed in last release.

**Closed by btcontract** 2022-01-12 18:09 UTC

**Comment by SkanderHelali** [comment] 2022-05-06 22:18
This seems to break any custom SSL port other than 50002 in my testing.
